# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bacterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'bacterial',
            },
        ),
        migrations.CreateModel(
            name='Genetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'genetic',
            },
        ),
        migrations.CreateModel(
            name='NonInfectious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'noninfectious',
            },
        ),
        migrations.CreateModel(
            name='Parasitic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'parasitic',
            },
        ),
        migrations.CreateModel(
            name='Viral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'viral',
            },
        ),
        migrations.CreateModel(
            name='VitaminMinerals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_affected', models.TextField(blank=True, db_column='System_affected', null=True)),
                ('organ_affected', models.TextField(blank=True, db_column='Organ_affected', null=True)),
                ('age_group', models.TextField(blank=True, db_column='Age_group', null=True)),
                ('disease_condition', models.TextField(blank=True, db_column='Disease_condition', null=True)),
                ('disease_row', models.TextField(blank=True, db_column='Disease_row', null=True)),
                ('type_of_organisms', models.TextField(blank=True, db_column='Type_of_organisms', null=True)),
                ('causative_agent', models.TextField(blank=True, db_column='Causative_agent', null=True)),
                ('am_findings', models.TextField(blank=True, db_column='AM_findings', null=True)),
                ('pm_findings', models.TextField(blank=True, db_column='PM_findings', null=True)),
                ('am_decision', models.TextField(blank=True, db_column='AM_Decision', null=True)),
                ('am', models.TextField(blank=True, db_column='AM', null=True)),
                ('pm_judgement', models.TextField(blank=True, db_column='PM_Judgement', null=True)),
                ('pm', models.TextField(blank=True, db_column='PM', null=True)),
            ],
            options={
                'db_table': 'vitaminminerals',
            },
        ),
    ]
